language: node_js
node_js:
  - "8.2.1"

services:
  - docker

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - node_modules/.bin/newman run json-placeholder.json -n 1
